# Generated by Django 3.1.5 on 2021-01-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('mac_address', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('last_heartbeat', models.DateTimeField()),
            ],
        ),
    ]
